name: Build ARM64 Linux Kernel (LLVM)

on:
  push:
    branches: [ "6f584e0" ]
  pull_request:
    branches: [ "6f584e0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Dependencies
      id: build_depends
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ccache lld clang llvm
    - name: Configure kernel
      run: ARCH=arm64 KBUILD_OUTPUT=build make "CC=ccache clang" LLVM=1 LLVM_IAS=1 gemstone_defconfig
    - name: Build kernel
      run: ARCH=arm64 KBUILD_OUTPUT=build make "CC=ccache clang" LLVM=1 LLVM_IAS=1 -j$(nproc)
    - name: Upload Build Artifact
      if: ${{ always() && steps.compile.outcome == 'success' }}
      uses: actions/upload-artifact@v6
      with:
        name: moonstone-kernel
        path: build/arch/arm64/boot/
