name: C/C++ CI

on:
  push:
    branches: [ "6f584e0" ]
  pull_request:
    branches: [ "6f584e0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Dependencies
      id: build_depends
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ccache gcc-aarch64-linux-gnu lld
    - name: configure
      run: export ARCH=arm64; export CROSS_COMPILE=aarch64-linux-gnu-
    - name: configure
      run: KBUILD_OUTPUT=build make "CC=ccache aarch64-linux-gnu-gcc" LLVM=1 gemstone_defconfig
    - name: compile
      run: KBUILD_OUTPUT=build make "CC=ccache aarch64-linux-gnu-gcc" LLVM=1 -j$(nproc)
    - name: Upload Build Artifact
      if: ${{ always() && steps.compile.outcome == 'success' }}
      uses: actions/upload-artifact@v6
      with:
        name: moonstone-kernel
        path: build/arch/arm64/boot/
