name: Build ARM64 Linux Kernel (LLVM)

on:
  push:
    branches: [ "6f584e0" ]
  pull_request:
    branches: [ "6f584e0" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Install Homebrew cross-toolchain & dependencies
      run: |
        brew install llvm
        brew tap messense/macos-cross-toolchains
        brew install aarch64-unknown-linux-gnu

    - name: Set environment variables
      run: |
        echo "KBUILD_OUTPUT=build" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-unknown-linux-gnu-" >> $GITHUB_ENV
        echo "PATH=/opt/homebrew/opt/llvm/bin:$PATH" >> $GITHUB_ENV

    - name: Clean kernel tree
      run: make -C ./mrproper

    - name: Configure kernel
      run: make -C ./ defconfig

    - name: Build Linux kernel with Clang
      id: gmake_build
      run: |
        make -C ./ -j$(sysctl -n hw.ncpu) CC=clang HOSTCC=clang LLVM=1

    - name: Archive built kernel
      if: ${{ always() && steps.gmake_build.outcome == 'success' }}
      uses: actions/upload-artifact@v6
      with:
        name: moonstone-kernel
        path: arch/arm64/boot/
