name: Build ARM64 Linux Kernel (LLVM)

on:
  push:
    branches: [ "6f584e0" ]
  pull_request:
    branches: [ "6f584e0" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Check libyaml version
      run: brew list libyaml; ls /opt/homebrew/Cellar/libyaml/0.2.5
    - name: Check clang version
      run: clang --version; make --version
    - name: Check sh version
      run: sh --version
    - name: Add GNU bash to PATH
      run:  echo /opt/homebrew/opt/bash/bin/ >> $GITHUB_PATH;export SHELL=/opt/homebrew/opt/bash/bin/bash;export PATH="/opt/homebrew/opt/bash/bin:$PATH"
    - name: Add GNU make to PATH
      run:  echo /opt/homebrew/opt/make/bin/ >> $GITHUB_PATH;export PATH="/opt/homebrew/opt/make/bin:$PATH"
    - name: Check sh version again
      run: sh --version; make --version
    - name: mkdir cache dir
      run: mkdir -p ~/.ccache
    - name: Install dependencies
      run: brew install ccache gnu-sed lld gmake
    - name: Add LLVM to PATH
      run:  echo $(brew --prefix llvm@22)/bin >> $GITHUB_PATH
    - name: Add GNU sed to PATH
      run:  echo /opt/homebrew/opt/gnu-sed/libexec/gnubin >> $GITHUB_PATH;echo /opt/homebrew/opt/make/libexec/gnubin/ >> $GITHUB_PATH
    - name: Show nproc
      run: sysctl -n hw.ncpu
    - name: Show sed version
      run: sed --version
    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.c', '**/*.cpp', '**/*.h') }}
        restore-keys: |
          ${{ runner.os }}-ccache-
    - name: Configure kernel
      run: ARCH=arm64 KBUILD_OUTPUT=build gmake "CC=ccache clang -I/opt/homebrew/Cellar/libyaml/0.2.5/include/ -L/opt/homebrew/Cellar/libyaml/0.2.5/lib/" \
        LLVM=1 LLVM_IAS=1 gemstone_defconfig
    - name: Build kernel
      id: gmake_build
      run: ARCH=arm64 KBUILD_OUTPUT=build gmake "CC=ccache clang" LLVM=1 LLVM_IAS=1 -j$(sysctl -n hw.ncpu)
    - name: Show ccache stats
      run: ccache -s
    - name: Upload Build Artifact
      if: ${{ always() && steps.gmake_build.outcome == 'success' }}
      uses: actions/upload-artifact@v6
      with:
        name: moonstone-kernel
        path: build/arch/arm64/boot/
