name: Build ARM64 Linux Kernel (LLVM)

on:
  push:
    branches: [ "6f584e0" ]
  pull_request:
    branches: [ "6f584e0" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Check clang version
      run: clang --version
    - name: mkdir cache dir
      run: mkdir -p ~/.ccache
    - name: Install dependencies
      run: brew install lld
    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.c', '**/*.cpp', '**/*.h') }}
        restore-keys: |
          ${{ runner.os }}-ccache-
    - name: Configure kernel
      run: ARCH=arm64 KBUILD_OUTPUT=build make "CC=ccache clang" LLVM=1 LLVM_IAS=1 gemstone_defconfig
    - name: Build kernel
      id: gmake_build
      run: ARCH=arm64 KBUILD_OUTPUT=build make "CC=ccache clang" LLVM=1 LLVM_IAS=1 -j$(nproc)
    - name: Show ccache stats
      run: ccache -s
    - name: Upload Build Artifact
      if: ${{ always() && steps.gmake_build.outcome == 'success' }}
      uses: actions/upload-artifact@v6
      with:
        name: moonstone-kernel
        path: build/arch/arm64/boot/
